name: Configuring your Azure environment

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  set-up-azure-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
  destroy-azure-resources:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
